# Generated by Django 4.0.4 on 2022-05-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'user'), ('mentor', 'mentor')], default='user', max_length=30),
        ),
    ]
