# Generated by Django 4.0.4 on 2022-06-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='booked_slot',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='booking_details',
            name='slot_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
