# Generated by Django 4.0.4 on 2022-06-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_details_slot_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='slot_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
