# Generated by Django 4.0.4 on 2022-05-15 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_domains'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qualification_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_price', models.FloatField()),
                ('mentor_desc', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('mentor_image', models.ImageField(upload_to='mentors')),
                ('Cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('Dom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.domains')),
                ('Qual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor.qualification')),
                ('mentoruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
