# Generated by Django 4.0.4 on 2022-05-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='mentor_image',
            field=models.ImageField(null=True, upload_to='mentors'),
        ),
    ]
