# Generated by Django 4.0.4 on 2022-06-04 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_domains'),
        ('mentor', '0002_alter_mentor_mentor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='Cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='Dom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.domains'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='Qual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentor.qualification'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mentor_desc',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mentor_image',
            field=models.ImageField(blank=True, null=True, upload_to='mentors'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mentor_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mentoruser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
