# Generated by Django 4.0.4 on 2022-06-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_alter_mentor_cat_alter_mentor_dom_alter_mentor_qual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='mentor_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
